// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ServiceIcon struct {
	ServiceID   string             `json:"service_id"`
	Content     []byte             `json:"content"`
	ContentType string             `json:"content_type"`
	ContentHash []byte             `json:"content_hash"`
	SourceEtag  *string            `json:"source_etag"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
}

type ServiceRole struct {
	ServiceID string `json:"service_id"`
	RoleKey   string `json:"role_key"`
	Name      string `json:"name"`
	Priority  int32  `json:"priority"`
	Active    bool   `json:"active"`
}

type ServiceRoleGroup struct {
	ServiceID string `json:"service_id"`
	RoleKey   string `json:"role_key"`
	OidcGroup string `json:"oidc_group"`
}
