// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonServiceRegistration = `-- name: AbandonServiceRegistration :execrows
UPDATE services
SET service_token_hash = NULL,
    registration_status = 'unregistered',
    availability_status = 'offline',
    health_error = 'service is unregistered',
    consecutive_health_failures = 0
WHERE id = $1
  AND registration_status = 'registering'
`

func (q *Queries) AbandonServiceRegistration(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, abandonServiceRegistration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimServiceRegistration = `-- name: ClaimServiceRegistration :one
INSERT INTO services (
    id,
    service_type,
    instance_id,
    name,
    version,
    internal_url,
    public_url,
    native_apps_url,
    service_token_hash,
    registration_status,
    created_at,
    last_seen_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 'registering', $10, $11
)
ON CONFLICT (service_type) DO UPDATE
SET instance_id = EXCLUDED.instance_id,
    name = EXCLUDED.name,
    version = EXCLUDED.version,
    internal_url = EXCLUDED.internal_url,
    service_token_hash = EXCLUDED.service_token_hash,
    registration_status = 'registering',
    availability_status = 'unknown',
    health_checked_at = NULL,
    health_error = NULL,
    consecutive_health_failures = 0,
    last_seen_at = EXCLUDED.last_seen_at
WHERE services.registration_status = 'unregistered'
RETURNING
    id,
    service_type,
    instance_id,
    name,
    version,
    internal_url,
    public_url,
    native_apps_url,
    default_role_key,
    database_host,
    database_port,
    database_name,
    database_username,
    provisioning_status,
    registration_status,
    availability_status,
    health_checked_at,
    health_error,
    consecutive_health_failures,
    created_at,
    last_seen_at
`

type ClaimServiceRegistrationParams struct {
	ID               string             `json:"id"`
	ServiceType      string             `json:"service_type"`
	InstanceID       string             `json:"instance_id"`
	Name             string             `json:"name"`
	Version          string             `json:"version"`
	InternalUrl      string             `json:"internal_url"`
	PublicUrl        string             `json:"public_url"`
	NativeAppsUrl    *string            `json:"native_apps_url"`
	ServiceTokenHash []byte             `json:"service_token_hash"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
}

type ClaimServiceRegistrationRow struct {
	ID                        string             `json:"id"`
	ServiceType               string             `json:"service_type"`
	InstanceID                string             `json:"instance_id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	InternalUrl               string             `json:"internal_url"`
	PublicUrl                 string             `json:"public_url"`
	NativeAppsUrl             *string            `json:"native_apps_url"`
	DefaultRoleKey            *string            `json:"default_role_key"`
	DatabaseHost              *string            `json:"database_host"`
	DatabasePort              *int32             `json:"database_port"`
	DatabaseName              *string            `json:"database_name"`
	DatabaseUsername          *string            `json:"database_username"`
	ProvisioningStatus        string             `json:"provisioning_status"`
	RegistrationStatus        string             `json:"registration_status"`
	AvailabilityStatus        string             `json:"availability_status"`
	HealthCheckedAt           pgtype.Timestamptz `json:"health_checked_at"`
	HealthError               *string            `json:"health_error"`
	ConsecutiveHealthFailures int32              `json:"consecutive_health_failures"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	LastSeenAt                pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ClaimServiceRegistration(ctx context.Context, arg ClaimServiceRegistrationParams) (ClaimServiceRegistrationRow, error) {
	row := q.db.QueryRow(ctx, claimServiceRegistration,
		arg.ID,
		arg.ServiceType,
		arg.InstanceID,
		arg.Name,
		arg.Version,
		arg.InternalUrl,
		arg.PublicUrl,
		arg.NativeAppsUrl,
		arg.ServiceTokenHash,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	var i ClaimServiceRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.InstanceID,
		&i.Name,
		&i.Version,
		&i.InternalUrl,
		&i.PublicUrl,
		&i.NativeAppsUrl,
		&i.DefaultRoleKey,
		&i.DatabaseHost,
		&i.DatabasePort,
		&i.DatabaseName,
		&i.DatabaseUsername,
		&i.ProvisioningStatus,
		&i.RegistrationStatus,
		&i.AvailabilityStatus,
		&i.HealthCheckedAt,
		&i.HealthError,
		&i.ConsecutiveHealthFailures,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const completeRoleCatalogRefresh = `-- name: CompleteRoleCatalogRefresh :execrows
UPDATE services
SET role_catalog_refreshed_at = $2,
    role_catalog_refresh_error = NULL
WHERE id = $1
`

type CompleteRoleCatalogRefreshParams struct {
	ID                     string             `json:"id"`
	RoleCatalogRefreshedAt pgtype.Timestamptz `json:"role_catalog_refreshed_at"`
}

func (q *Queries) CompleteRoleCatalogRefresh(ctx context.Context, arg CompleteRoleCatalogRefreshParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRoleCatalogRefresh, arg.ID, arg.RoleCatalogRefreshedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeServiceProvisioning = `-- name: CompleteServiceProvisioning :execrows
UPDATE services
SET database_host = $2,
    database_port = $3,
    database_name = $4,
    database_username = $5,
    provisioning_status = 'registered',
    registration_status = 'registered'
WHERE id = $1
`

type CompleteServiceProvisioningParams struct {
	ID               string  `json:"id"`
	DatabaseHost     *string `json:"database_host"`
	DatabasePort     *int32  `json:"database_port"`
	DatabaseName     *string `json:"database_name"`
	DatabaseUsername *string `json:"database_username"`
}

func (q *Queries) CompleteServiceProvisioning(ctx context.Context, arg CompleteServiceProvisioningParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeServiceProvisioning,
		arg.ID,
		arg.DatabaseHost,
		arg.DatabasePort,
		arg.DatabaseName,
		arg.DatabaseUsername,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createServiceRoleGroup = `-- name: CreateServiceRoleGroup :exec
INSERT INTO service_role_groups (service_id, role_key, oidc_group)
VALUES ($1, $2, $3)
`

type CreateServiceRoleGroupParams struct {
	ServiceID string `json:"service_id"`
	RoleKey   string `json:"role_key"`
	OidcGroup string `json:"oidc_group"`
}

func (q *Queries) CreateServiceRoleGroup(ctx context.Context, arg CreateServiceRoleGroupParams) error {
	_, err := q.db.Exec(ctx, createServiceRoleGroup, arg.ServiceID, arg.RoleKey, arg.OidcGroup)
	return err
}

const deactivateServiceRoles = `-- name: DeactivateServiceRoles :exec
UPDATE service_roles
SET active = FALSE
WHERE service_id = $1
`

func (q *Queries) DeactivateServiceRoles(ctx context.Context, serviceID string) error {
	_, err := q.db.Exec(ctx, deactivateServiceRoles, serviceID)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const deleteServiceRoleGroups = `-- name: DeleteServiceRoleGroups :exec
DELETE FROM service_role_groups
WHERE service_id = $1
`

func (q *Queries) DeleteServiceRoleGroups(ctx context.Context, serviceID string) error {
	_, err := q.db.Exec(ctx, deleteServiceRoleGroups, serviceID)
	return err
}

const ensureCoreService = `-- name: EnsureCoreService :one
INSERT INTO services (
    id,
    service_type,
    instance_id,
    name,
    version,
    internal_url,
    service_token_hash,
    provisioning_status,
    registration_status,
    availability_status,
    health_checked_at,
    created_at,
    last_seen_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NULL, 'registered', 'registered', 'online', $8, $7, $8
)
ON CONFLICT (service_type) DO UPDATE
SET instance_id = EXCLUDED.instance_id,
    name = EXCLUDED.name,
    version = EXCLUDED.version,
    internal_url = EXCLUDED.internal_url,
    service_token_hash = NULL,
    database_host = NULL,
    database_port = NULL,
    database_name = NULL,
    database_username = NULL,
    default_role_key = NULL,
    provisioning_status = 'registered',
    registration_status = 'registered',
    availability_status = 'online',
    health_checked_at = EXCLUDED.last_seen_at,
    health_error = NULL,
    consecutive_health_failures = 0,
    last_seen_at = EXCLUDED.last_seen_at
RETURNING id
`

type EnsureCoreServiceParams struct {
	ID              string             `json:"id"`
	ServiceType     string             `json:"service_type"`
	InstanceID      string             `json:"instance_id"`
	Name            string             `json:"name"`
	Version         string             `json:"version"`
	InternalUrl     string             `json:"internal_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	HealthCheckedAt pgtype.Timestamptz `json:"health_checked_at"`
}

func (q *Queries) EnsureCoreService(ctx context.Context, arg EnsureCoreServiceParams) (string, error) {
	row := q.db.QueryRow(ctx, ensureCoreService,
		arg.ID,
		arg.ServiceType,
		arg.InstanceID,
		arg.Name,
		arg.Version,
		arg.InternalUrl,
		arg.CreatedAt,
		arg.HealthCheckedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT
    id,
    service_type,
    instance_id,
    name,
    version,
    internal_url,
    public_url,
    native_apps_url,
    default_role_key,
    role_catalog_refreshed_at,
    role_catalog_refresh_error,
    database_host,
    database_port,
    database_name,
    database_username,
    provisioning_status,
    registration_status,
    availability_status,
    health_checked_at,
    health_error,
    consecutive_health_failures,
    created_at,
    last_seen_at
FROM services
WHERE id = $1
`

type GetServiceByIDRow struct {
	ID                        string             `json:"id"`
	ServiceType               string             `json:"service_type"`
	InstanceID                string             `json:"instance_id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	InternalUrl               string             `json:"internal_url"`
	PublicUrl                 string             `json:"public_url"`
	NativeAppsUrl             *string            `json:"native_apps_url"`
	DefaultRoleKey            *string            `json:"default_role_key"`
	RoleCatalogRefreshedAt    pgtype.Timestamptz `json:"role_catalog_refreshed_at"`
	RoleCatalogRefreshError   *string            `json:"role_catalog_refresh_error"`
	DatabaseHost              *string            `json:"database_host"`
	DatabasePort              *int32             `json:"database_port"`
	DatabaseName              *string            `json:"database_name"`
	DatabaseUsername          *string            `json:"database_username"`
	ProvisioningStatus        string             `json:"provisioning_status"`
	RegistrationStatus        string             `json:"registration_status"`
	AvailabilityStatus        string             `json:"availability_status"`
	HealthCheckedAt           pgtype.Timestamptz `json:"health_checked_at"`
	HealthError               *string            `json:"health_error"`
	ConsecutiveHealthFailures int32              `json:"consecutive_health_failures"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	LastSeenAt                pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) GetServiceByID(ctx context.Context, id string) (GetServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i GetServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.InstanceID,
		&i.Name,
		&i.Version,
		&i.InternalUrl,
		&i.PublicUrl,
		&i.NativeAppsUrl,
		&i.DefaultRoleKey,
		&i.RoleCatalogRefreshedAt,
		&i.RoleCatalogRefreshError,
		&i.DatabaseHost,
		&i.DatabasePort,
		&i.DatabaseName,
		&i.DatabaseUsername,
		&i.ProvisioningStatus,
		&i.RegistrationStatus,
		&i.AvailabilityStatus,
		&i.HealthCheckedAt,
		&i.HealthError,
		&i.ConsecutiveHealthFailures,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getServiceByInstanceID = `-- name: GetServiceByInstanceID :one
SELECT
    id,
    service_type,
    instance_id,
    name,
    version,
    internal_url,
    public_url,
    native_apps_url,
    default_role_key,
    database_host,
    database_port,
    database_name,
    database_username,
    provisioning_status,
    registration_status,
    availability_status,
    health_checked_at,
    health_error,
    consecutive_health_failures,
    created_at,
    last_seen_at
FROM services
WHERE instance_id = $1
`

type GetServiceByInstanceIDRow struct {
	ID                        string             `json:"id"`
	ServiceType               string             `json:"service_type"`
	InstanceID                string             `json:"instance_id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	InternalUrl               string             `json:"internal_url"`
	PublicUrl                 string             `json:"public_url"`
	NativeAppsUrl             *string            `json:"native_apps_url"`
	DefaultRoleKey            *string            `json:"default_role_key"`
	DatabaseHost              *string            `json:"database_host"`
	DatabasePort              *int32             `json:"database_port"`
	DatabaseName              *string            `json:"database_name"`
	DatabaseUsername          *string            `json:"database_username"`
	ProvisioningStatus        string             `json:"provisioning_status"`
	RegistrationStatus        string             `json:"registration_status"`
	AvailabilityStatus        string             `json:"availability_status"`
	HealthCheckedAt           pgtype.Timestamptz `json:"health_checked_at"`
	HealthError               *string            `json:"health_error"`
	ConsecutiveHealthFailures int32              `json:"consecutive_health_failures"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	LastSeenAt                pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) GetServiceByInstanceID(ctx context.Context, instanceID string) (GetServiceByInstanceIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByInstanceID, instanceID)
	var i GetServiceByInstanceIDRow
	err := row.Scan(
		&i.ID,
		&i.ServiceType,
		&i.InstanceID,
		&i.Name,
		&i.Version,
		&i.InternalUrl,
		&i.PublicUrl,
		&i.NativeAppsUrl,
		&i.DefaultRoleKey,
		&i.DatabaseHost,
		&i.DatabasePort,
		&i.DatabaseName,
		&i.DatabaseUsername,
		&i.ProvisioningStatus,
		&i.RegistrationStatus,
		&i.AvailabilityStatus,
		&i.HealthCheckedAt,
		&i.HealthError,
		&i.ConsecutiveHealthFailures,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getServiceIcon = `-- name: GetServiceIcon :one
SELECT service_id, content, content_type, content_hash, source_etag, fetched_at
FROM service_icons
WHERE service_id = $1
`

func (q *Queries) GetServiceIcon(ctx context.Context, serviceID string) (ServiceIcon, error) {
	row := q.db.QueryRow(ctx, getServiceIcon, serviceID)
	var i ServiceIcon
	err := row.Scan(
		&i.ServiceID,
		&i.Content,
		&i.ContentType,
		&i.ContentHash,
		&i.SourceEtag,
		&i.FetchedAt,
	)
	return i, err
}

const getServiceTokenHash = `-- name: GetServiceTokenHash :one
SELECT service_token_hash
FROM services
WHERE id = $1
`

func (q *Queries) GetServiceTokenHash(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getServiceTokenHash, id)
	var service_token_hash []byte
	err := row.Scan(&service_token_hash)
	return service_token_hash, err
}

const listServiceRoleGroups = `-- name: ListServiceRoleGroups :many
SELECT groups.service_id, groups.role_key, groups.oidc_group
FROM service_role_groups AS groups
JOIN service_roles AS roles
    ON roles.service_id = groups.service_id
    AND roles.role_key = groups.role_key
WHERE groups.service_id = $1
ORDER BY roles.priority DESC, groups.role_key, groups.oidc_group
`

func (q *Queries) ListServiceRoleGroups(ctx context.Context, serviceID string) ([]ServiceRoleGroup, error) {
	rows, err := q.db.Query(ctx, listServiceRoleGroups, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceRoleGroup{}
	for rows.Next() {
		var i ServiceRoleGroup
		if err := rows.Scan(&i.ServiceID, &i.RoleKey, &i.OidcGroup); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRoles = `-- name: ListServiceRoles :many
SELECT service_id, role_key, name, priority, active
FROM service_roles
WHERE service_id = $1
ORDER BY active DESC, priority DESC, role_key
`

func (q *Queries) ListServiceRoles(ctx context.Context, serviceID string) ([]ServiceRole, error) {
	rows, err := q.db.Query(ctx, listServiceRoles, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceRole{}
	for rows.Next() {
		var i ServiceRole
		if err := rows.Scan(
			&i.ServiceID,
			&i.RoleKey,
			&i.Name,
			&i.Priority,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT
    id,
    service_type,
    instance_id,
    name,
    version,
    internal_url,
    public_url,
    native_apps_url,
    default_role_key,
    database_host,
    database_port,
    database_name,
    database_username,
    provisioning_status,
    registration_status,
    availability_status,
    health_checked_at,
    health_error,
    consecutive_health_failures,
    created_at,
    last_seen_at
FROM services
ORDER BY CASE WHEN service_type = 'core' THEN 0 ELSE 1 END, name, id
`

type ListServicesRow struct {
	ID                        string             `json:"id"`
	ServiceType               string             `json:"service_type"`
	InstanceID                string             `json:"instance_id"`
	Name                      string             `json:"name"`
	Version                   string             `json:"version"`
	InternalUrl               string             `json:"internal_url"`
	PublicUrl                 string             `json:"public_url"`
	NativeAppsUrl             *string            `json:"native_apps_url"`
	DefaultRoleKey            *string            `json:"default_role_key"`
	DatabaseHost              *string            `json:"database_host"`
	DatabasePort              *int32             `json:"database_port"`
	DatabaseName              *string            `json:"database_name"`
	DatabaseUsername          *string            `json:"database_username"`
	ProvisioningStatus        string             `json:"provisioning_status"`
	RegistrationStatus        string             `json:"registration_status"`
	AvailabilityStatus        string             `json:"availability_status"`
	HealthCheckedAt           pgtype.Timestamptz `json:"health_checked_at"`
	HealthError               *string            `json:"health_error"`
	ConsecutiveHealthFailures int32              `json:"consecutive_health_failures"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	LastSeenAt                pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceType,
			&i.InstanceID,
			&i.Name,
			&i.Version,
			&i.InternalUrl,
			&i.PublicUrl,
			&i.NativeAppsUrl,
			&i.DefaultRoleKey,
			&i.DatabaseHost,
			&i.DatabasePort,
			&i.DatabaseName,
			&i.DatabaseUsername,
			&i.ProvisioningStatus,
			&i.RegistrationStatus,
			&i.AvailabilityStatus,
			&i.HealthCheckedAt,
			&i.HealthError,
			&i.ConsecutiveHealthFailures,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForHealthCheck = `-- name: ListServicesForHealthCheck :many
SELECT id, internal_url
FROM services
WHERE registration_status = 'registered'
  AND service_type <> 'core'
ORDER BY id
`

type ListServicesForHealthCheckRow struct {
	ID          string `json:"id"`
	InternalUrl string `json:"internal_url"`
}

func (q *Queries) ListServicesForHealthCheck(ctx context.Context) ([]ListServicesForHealthCheckRow, error) {
	rows, err := q.db.Query(ctx, listServicesForHealthCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesForHealthCheckRow{}
	for rows.Next() {
		var i ListServicesForHealthCheckRow
		if err := rows.Scan(&i.ID, &i.InternalUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRegisteredServicesHealthUnknown = `-- name: MarkRegisteredServicesHealthUnknown :exec
UPDATE services
SET availability_status = 'unknown',
    health_checked_at = NULL,
    health_error = NULL,
    consecutive_health_failures = 0
WHERE registration_status = 'registered'
  AND service_type <> 'core'
`

func (q *Queries) MarkRegisteredServicesHealthUnknown(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markRegisteredServicesHealthUnknown)
	return err
}

const recordRoleCatalogRefreshFailure = `-- name: RecordRoleCatalogRefreshFailure :execrows
UPDATE services
SET role_catalog_refresh_error = $2
WHERE id = $1
`

type RecordRoleCatalogRefreshFailureParams struct {
	ID                      string  `json:"id"`
	RoleCatalogRefreshError *string `json:"role_catalog_refresh_error"`
}

func (q *Queries) RecordRoleCatalogRefreshFailure(ctx context.Context, arg RecordRoleCatalogRefreshFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordRoleCatalogRefreshFailure, arg.ID, arg.RoleCatalogRefreshError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordServiceHealthFailure = `-- name: RecordServiceHealthFailure :execrows
UPDATE services
SET availability_status = CASE
        WHEN availability_status = 'unknown'
          OR consecutive_health_failures + 1 >= $4
        THEN 'offline'
        ELSE availability_status
    END,
    health_checked_at = $2,
    health_error = $3,
    consecutive_health_failures = consecutive_health_failures + 1
WHERE id = $1
  AND registration_status = 'registered'
`

type RecordServiceHealthFailureParams struct {
	ID                        string             `json:"id"`
	HealthCheckedAt           pgtype.Timestamptz `json:"health_checked_at"`
	HealthError               *string            `json:"health_error"`
	ConsecutiveHealthFailures int32              `json:"consecutive_health_failures"`
}

func (q *Queries) RecordServiceHealthFailure(ctx context.Context, arg RecordServiceHealthFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordServiceHealthFailure,
		arg.ID,
		arg.HealthCheckedAt,
		arg.HealthError,
		arg.ConsecutiveHealthFailures,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordServiceHealthSuccess = `-- name: RecordServiceHealthSuccess :execrows
UPDATE services
SET availability_status = 'online',
    health_checked_at = $2,
    health_error = NULL,
    consecutive_health_failures = 0,
    last_seen_at = $2
WHERE id = $1
  AND registration_status = 'registered'
`

type RecordServiceHealthSuccessParams struct {
	ID              string             `json:"id"`
	HealthCheckedAt pgtype.Timestamptz `json:"health_checked_at"`
}

func (q *Queries) RecordServiceHealthSuccess(ctx context.Context, arg RecordServiceHealthSuccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordServiceHealthSuccess, arg.ID, arg.HealthCheckedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordServiceHealthUnavailable = `-- name: RecordServiceHealthUnavailable :execrows
UPDATE services
SET availability_status = 'offline',
    health_checked_at = $2,
    health_error = 'service reported itself unavailable',
    consecutive_health_failures = 0,
    last_seen_at = $2
WHERE id = $1
  AND registration_status = 'registered'
`

type RecordServiceHealthUnavailableParams struct {
	ID              string             `json:"id"`
	HealthCheckedAt pgtype.Timestamptz `json:"health_checked_at"`
}

func (q *Queries) RecordServiceHealthUnavailable(ctx context.Context, arg RecordServiceHealthUnavailableParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordServiceHealthUnavailable, arg.ID, arg.HealthCheckedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unregisterService = `-- name: UnregisterService :execrows
UPDATE services
SET service_token_hash = NULL,
    registration_status = 'unregistered',
    availability_status = 'offline',
    health_error = 'service is unregistered',
    consecutive_health_failures = 0,
    role_catalog_refresh_error = 'service is unregistered'
WHERE id = $1
  AND registration_status = 'registered'
`

func (q *Queries) UnregisterService(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, unregisterService, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateServiceConfiguration = `-- name: UpdateServiceConfiguration :execrows
UPDATE services
SET public_url = $2,
    native_apps_url = $3,
    default_role_key = $4
WHERE id = $1
`

type UpdateServiceConfigurationParams struct {
	ID             string  `json:"id"`
	PublicUrl      string  `json:"public_url"`
	NativeAppsUrl  *string `json:"native_apps_url"`
	DefaultRoleKey *string `json:"default_role_key"`
}

func (q *Queries) UpdateServiceConfiguration(ctx context.Context, arg UpdateServiceConfigurationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceConfiguration,
		arg.ID,
		arg.PublicUrl,
		arg.NativeAppsUrl,
		arg.DefaultRoleKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertServiceIcon = `-- name: UpsertServiceIcon :exec
INSERT INTO service_icons (
    service_id,
    content,
    content_type,
    content_hash,
    source_etag,
    fetched_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (service_id) DO UPDATE
SET content = EXCLUDED.content,
    content_type = EXCLUDED.content_type,
    content_hash = EXCLUDED.content_hash,
    source_etag = EXCLUDED.source_etag,
    fetched_at = EXCLUDED.fetched_at
`

type UpsertServiceIconParams struct {
	ServiceID   string             `json:"service_id"`
	Content     []byte             `json:"content"`
	ContentType string             `json:"content_type"`
	ContentHash []byte             `json:"content_hash"`
	SourceEtag  *string            `json:"source_etag"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) UpsertServiceIcon(ctx context.Context, arg UpsertServiceIconParams) error {
	_, err := q.db.Exec(ctx, upsertServiceIcon,
		arg.ServiceID,
		arg.Content,
		arg.ContentType,
		arg.ContentHash,
		arg.SourceEtag,
		arg.FetchedAt,
	)
	return err
}

const upsertServiceRole = `-- name: UpsertServiceRole :exec
INSERT INTO service_roles (service_id, role_key, name, priority, active)
VALUES ($1, $2, $3, $4, TRUE)
ON CONFLICT (service_id, role_key) DO UPDATE
SET name = EXCLUDED.name,
    priority = EXCLUDED.priority,
    active = TRUE
`

type UpsertServiceRoleParams struct {
	ServiceID string `json:"service_id"`
	RoleKey   string `json:"role_key"`
	Name      string `json:"name"`
	Priority  int32  `json:"priority"`
}

func (q *Queries) UpsertServiceRole(ctx context.Context, arg UpsertServiceRoleParams) error {
	_, err := q.db.Exec(ctx, upsertServiceRole,
		arg.ServiceID,
		arg.RoleKey,
		arg.Name,
		arg.Priority,
	)
	return err
}
